---
- hosts: all
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want copy my file into node side
    copy:
      src: manistatefile
      dest: /home/maha/manistatefile

  - name: i want copy my file into node side
    template:
      src: manyindex.j2
      dest: /var/www/html/index.html