---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i want install apache2 (apt-get install apache2)
    apt: 
      name: apache2
      state: present 
    when: ansible_os_family=="Debian"  
  - name: i want install apache2 (yum install httpd)
    dnf: 
      name: httpd
      state: present 
    when: ansible_os_family=="Redhat"