---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want install java on mydebian node
    apt:
     name: 
     state: present
    when: ansible_os_family=="Debian" 

  - name: i want install java on redhat node
    dnf:
     name: 
     state: present
    when: ansible_os_family=="RedHat"
     
      